
path: /Users/julesdesir/Documents/Etudes/Mines-Paris/2A/Autres/Data-challenge-Capgemini-novembre-2023/YOLO-Attempt/data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val # val images (relative to 'path')
test: images/test # test images (relative to 'path')

# List here all the classes and their id number
names:
  0: Toyota Sequoia SUV 2012
  1: Toyota Camry Sedan 2012
  2: Toyota Corolla Sedan 2012
  3: Volkswagen Beetle Hatchback 2012
  4: Volvo C30 Hatchback 2012
  5: Volvo 240 Sedan 1993
  6: Volvo XC90 SUV 2007
  7: Audi S5 Convertible 2012
  8: Audi S5 Coupe 2012
  9: Audi S4 Sedan 2007
  10: Audi TT RS Coupe 2012
  11: BMW ActiveHybrid 5 Sedan 2012
  12: BMW 1 Series Convertible 2012
  13: BMW 1 Series Coupe 2012
  14: BMW 3 Series Wagon 2012
  15: Acura TL Type-S 2008
  16: BMW X6 SUV 2012
  17: AM General Hummer SUV 2000
  18: BMW M5 Sedan 2010
  19: Bentley Continental GT Coupe 2007
  20: Buick Regal GS 2012
  21: Buick Rainier SUV 2007
  22: Cadillac SRX SUV 2012
  23: Chevrolet Corvette ZR1 2012
  24: Chevrolet Camaro Convertible 2012
  25: Chevrolet HHR SS 2010
  26: Acura ZDX Hatchback 2012
  27: Chevrolet Cobalt SS 2010
  28: Chevrolet TrailBlazer SS 2009
  29: Chevrolet Silverado 1500 Classic Extended Cab 2007
  30: Chevrolet Express Van 2007
  31: Aston Martin V8 Vantage Convertible 2012
  32: Chevrolet Malibu Sedan 2007
  33: Chevrolet Silverado 1500 Extended Cab 2012
  34: Chrysler 300 SRT-8 2010
  35: Chrysler Crossfire Convertible 2008
  36: Chrysler PT Cruiser Convertible 2008
  37: Aston Martin V8 Vantage Coupe 2012
  38: Dodge Caliber Wagon 2012
  39: Dodge Caliber Wagon 2007
  40: Dodge Magnum Wagon 2008
  41: Aston Martin Virage Convertible 2012
  42: Dodge Durango SUV 2007
  43: Dodge Charger Sedan 2012
  44: Eagle Talon Hatchback 1998
  45: FIAT 500 Convertible 2012
  46: Aston Martin Virage Coupe 2012
  47: Ferrari 458 Italia Convertible 2012
  48: Ferrari 458 Italia Coupe 2012
  49: Fisker Karma Sedan 2012
  50: Ford F-450 Super Duty Crew Cab 2012
  51: Ford Mustang Convertible 2007
  52: Ford Freestar Minivan 2007
  53: Ford Expedition EL SUV 2009
  54: Ford Ranger SuperCab 2011
  55: Ford GT Coupe 2006
  56: Ford F-150 Regular Cab 2007
  57: Ford Focus Sedan 2007
  58: Ford E-Series Wagon Van 2012
  59: Ford Fiesta Sedan 2012
  60: Audi A5 Coupe 2012
  61: GMC Yukon Hybrid SUV 2012
  62: HUMMER H3T Crew Cab 2010
  63: Honda Odyssey Minivan 2012
  64: Audi TTS Coupe 2012
  65: Honda Accord Coupe 2012
  66: Hyundai Veracruz SUV 2012
  67: Hyundai Sonata Hybrid Sedan 2012
  68: Hyundai Genesis Sedan 2012
  69: Hyundai Sonata Sedan 2012
  70: Hyundai Azera Sedan 2012
  71: Infiniti G Coupe IPL 2012
  72: Infiniti QX56 SUV 2011
  73: Jaguar XK XKR 2012
  74: Jeep Wrangler SUV 2012
  75: Jeep Liberty SUV 2012
  76: Jeep Grand Cherokee SUV 2012
  77: Audi V8 Sedan 1994
  78: Lamborghini Reventon Coupe 2008
  79: Lamborghini Aventador Coupe 2012
  80: Lamborghini Gallardo LP 570-4 Superleggera 2012
  81: Land Rover LR2 SUV 2012
  82: Maybach Landaulet Convertible 2012
  83: Audi 100 Sedan 1994
  84: Mercedes-Benz 300-Class Convertible 1993
  85: Mercedes-Benz SL-Class Coupe 2009
  86: Mercedes-Benz Sprinter Van 2012
  87: Mitsubishi Lancer Sedan 2012
  88: Nissan Leaf Hatchback 2012
  89: Audi 100 Wagon 1994
  90: Plymouth Neon Coupe 1999
  91: Porsche Panamera Sedan 2012
  92: Rolls-Royce Phantom Drophead Coupe Convertible 2012
  93: Rolls-Royce Ghost Sedan 2012
  94: Rolls-Royce Phantom Sedan 2012
  95: Scion xD Hatchback 2012
  96: Spyker C8 Coupe 2009
  97: Suzuki Aerio Sedan 2007
  98: Suzuki Kizashi Sedan 2012
  99: Suzuki SX4 Sedan 2012
